### ISSUE TITLE
projects incomplete

### ISSUE THREAD

**Issue by hachem9** [AmrKhalil97/E-Commerce-flutter-application#1]
missing whole lib folder

**Comment by AmrKhalil97** [comment]
Thank you for reaching out. I've posted the whole project before. I removed the lib folder because my client asked me to put the code on github when the app is published. If you want farther information about this project please send me an email on amr.hisham.khalil@gmail.com or join the discord server on my profile.

**Comment by xebbinoo** [comment]
solved!
